In [1]:
import os
import numpy as np
np.set_printoptions(suppress=True)

from scipy.spatial.transform import Rotation

import poselib

## There is two ways to apply extrinsics

In [2]:
x = np.array([1., 1., 1.])

In [3]:
R = Rotation.random().as_matrix()
c = np.random.rand(3)

In [4]:
R, c

(array([[ 0.16994507, -0.79517698,  0.58207581],
        [ 0.97736599,  0.2115247 ,  0.00360956],
        [-0.12599365,  0.56828767,  0.81312651]]),
 array([0.84019357, 0.50069239, 0.2279258 ]))

In [5]:
x2d_t = R @ (x - c) # translate first then rotate

In [6]:
x2d_t

array([0.07952611, 0.26459212, 0.89140976])

In [7]:
R.T @ x2d_t + c

array([1., 1., 1.])

In [8]:
t = - R @ c

In [9]:
x2d_r = R @ x + t # rotate first then translate

In [10]:
x2d_r

array([0.07952611, 0.26459212, 0.89140976])

In [11]:
R.T @ (x2d_r - t)

array([1., 1., 1.])

## Projections!

In [22]:
# those taken from ground truth
c = np.array([-1.495227, 0.04562, -10.339456])
q = np.array([0.901882, -0.251623, -0.34861, 0.042019])

# note the inconsistency

qmtx = Rotation.from_quat([*q[1:], q[0]]) # x, y, z, w
qmtx.as_matrix()

array([[ 0.75341089,  0.09964425, -0.64995619],
       [ 0.251229  ,  0.86984051,  0.4245721 ],
       [ 0.60766439, -0.48316509,  0.6303138 ]])

In [23]:
gt_pose = poselib.CameraPose()
gt_pose.q = q

In [24]:
R = gt_pose.R

In [25]:
# example pair taken from the experiment
x = np.array([192.12533569, 19.14378548])
X = np.array([11.86180782, -14.56327057, -0.92378181])

In [26]:
t = -R @ c

In [27]:
R, t

(array([[ 0.75341094,  0.09964423, -0.64995606],
        [ 0.25122895,  0.86984054,  0.42457202],
        [ 0.60766427, -0.483165  ,  0.63031387]]),
 array([-5.59821749,  4.72580592,  7.44774052]))

In [28]:
# SIMPLE_RADIAL
camera = {'f': 277.4716064453125, 'cx': 160.0, 'cy': 90.0, 'w': 320, 'h': 180}

In [29]:
def pix2cam(x, camera):
    x = np.concatenate([x, np.ones(1)])
    x[0] -= camera["cx"]
    x[1] -= camera["cy"]
    x[:2] /= camera["f"]
    x /= np.linalg.norm(x)
    
    return x

def cam2pix(x, camera):
    x /= x[2]
    x[:2] *= camera["f"]
    x[0] += camera["cx"]
    x[1] += camera["cy"]
    
    return x

def w2c(X, R, t):
    return R @ X + t

cam2pix(w2c(X.copy(), R, t), camera)

array([192.70088458,  19.62502469,   1.        ])

In [32]:
cam2pix(pix2cam(x.copy(), camera), camera)[:2]

array([192.12533569,  19.14378548])

In [33]:
X

array([ 11.86180782, -14.56327057,  -0.92378181])

In [34]:
x, pix2cam(x.copy(), camera)

(array([192.12533569,  19.14378548]),
 array([ 0.11147971, -0.24588163,  0.96286785]))

In [35]:
w2c(X.copy(), R, t), cam2pix(w2c(X.copy(), R, t), camera)

(array([ 2.48787005, -5.35409962, 21.10992744]),
 array([192.70088458,  19.62502469,   1.        ]))

In [36]:
'''
// params = f, cx, cy, k1

void SimpleRadialCameraModel::project(const std::vector<double> &params, const Eigen::Vector2d &x,
                                      Eigen::Vector2d *xp) {
    const double r2 = x.squaredNorm();
    const double alpha = (1.0 + params[3] * r2);
    (*xp)(0) = params[0] * alpha * x(0) + params[1];
    (*xp)(1) = params[0] * alpha * x(1) + params[2];
}

void SimpleRadialCameraModel::unproject(const std::vector<double> &params, const Eigen::Vector2d &xp,
                                        Eigen::Vector2d *x) {
    (*x)(0) = (xp(0) - params[1]) / params[0];
    (*x)(1) = (xp(1) - params[2]) / params[0];
    double r0 = x->norm();
    double r = undistort_poly1(params[3], r0);
    (*x) *= r / r0;
}
'''

'\n// params = f, cx, cy, k1\n\nvoid SimpleRadialCameraModel::project(const std::vector<double> &params, const Eigen::Vector2d &x,\n                                      Eigen::Vector2d *xp) {\n    const double r2 = x.squaredNorm();\n    const double alpha = (1.0 + params[3] * r2);\n    (*xp)(0) = params[0] * alpha * x(0) + params[1];\n    (*xp)(1) = params[0] * alpha * x(1) + params[2];\n}\n\nvoid SimpleRadialCameraModel::unproject(const std::vector<double> &params, const Eigen::Vector2d &xp,\n                                        Eigen::Vector2d *x) {\n    (*x)(0) = (xp(0) - params[1]) / params[0];\n    (*x)(1) = (xp(1) - params[2]) / params[0];\n    double r0 = x->norm();\n    double r = undistort_poly1(params[3], r0);\n    (*x) *= r / r0;\n}\n'

```c++
const Eigen::Matrix3d R = pose.R();
const double P0_0 = R(0, 0), P0_1 = R(0, 1), P0_2 = R(0, 2), P0_3 = pose.t(0);
const double P1_0 = R(1, 0), P1_1 = R(1, 1), P1_2 = R(1, 2), P1_3 = pose.t(1);
const double P2_0 = R(2, 0), P2_1 = R(2, 1), P2_2 = R(2, 2), P2_3 = pose.t(2);

const double X0 = X[k](0), X1 = X[k](1), X2 = X[k](2);
const double x0 = x[k](0), x1 = x[k](1);

// P00 P01 P02 P03 | X0 
// P10 P11 P12 P13 | X1 
// P20 P21 P22 P23 | X2
// 0   0   0   0   | 1

const double z0 = P0_0 * X0 + P0_1 * X1 + P0_2 * X2 + P0_3;
const double z1 = P1_0 * X0 + P1_1 * X1 + P1_2 * X2 + P1_3;
const double z2 = P2_0 * X0 + P2_1 * X1 + P2_2 * X2 + P2_3;
const double inv_z2 = 1.0 / z2;

const double r_0 = z0 * inv_z2 - x0;
const double r_1 = z1 * inv_z2 - x1;
const double r_sq = r_0 * r_0 + r_1 * r_1;
```